BOT_API = ''

BOT_ID = ''

FOREX_CHANNEL_ID = ''

MY_SIGNALS_CHANNEL = ''

GROUP_ID = ''

PERSONAL_API = ''

PERSONAL_HASH = ''

FILE_PATH = ''

#list of all forex pairs you want to trade with the bot
TRADE_LIST = ['AUDCAD', 'AUDCHF', 'AUDJPY', 'AUDNZD', 'AUDUSD', 'CADCHF', 'CADJPY', 'CHFJPY', 'EURAUD', 'EURCAD', 'EURCHF', 'EURGBP', 'EURJPY', 'EURNZD',
            'EURUSD', 'GBPAUD', 'GBPCAD', 'GBPCHF', 'GBPJPY', 'GBPNZD', 'GBPUSD', 'NZDCAD', 'NZDCHF', 'NZDJPY', 'NZDUSD', 'USDCAD', 'USDCHF', 'USDJPY',
            'XAUUSD', 'XAGUSD', 'XPTUSD', 'XPDUSD', 'XBRUSD', 'XNGUSD', 'XCUUSD', 'XPDUSD']

REMOVE_LIST = []

NEW_SIGNAL = ""